
runtime: python39
#env: flex

# You CAN configure this even in standard environment. Presumably
# by default, it is what you see below
#entrypoint: gunicorn -b :$PORT main:app

#runtime_config:
#  python_version: 3

handlers:
- url: /.*
  secure: always  # Requires https
  script: auto

# There is concern about something triggering huge increase in instances 
# resulting in high bills. This may require some reconsideration if people 
# really begin using the service. 
basic_scaling:
  max_instances: 2

env_variables:
  TARGET_SERVICE_URL: "https://healthcare.googleapis.com/v1/projects/anvil-fhir-vumc/locations/us/datasets/anvil-research-studies/fhirStores/research-study/fhir"
